# Generated by Django 5.2.14 on 2026-06-16 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movement_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='status',
            field=models.CharField(choices=[('working', 'Рабочий'), ('broken', 'Нерабочий'), ('unknown', 'Неизвестно'), ('repair', 'Ремонт')], default='unknown', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата ухода'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата поступления'),
        ),
    ]
