# Generated by Django 5.2.15 on 2026-08-24 10:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def normalize_zero_document_quantities(apps, schema_editor):
    AuditLog = apps.get_model("inventory", "AuditLog")
    corrected = []
    for model_name, label in (
        ("Receipt", "Поступления"),
        ("Disposal", "Уходы"),
        ("Order", "Заказы"),
    ):
        model = apps.get_model("inventory", model_name)
        count = model.objects.filter(quantity__lt=1).update(quantity=1)
        if count:
            corrected.append(f"{label}: {count}")

    if corrected:
        AuditLog.objects.create(
            action="system",
            object_type="data_migration",
            object_type_label="Миграция данных",
            object_repr="Исправлены нулевые количества документов",
            note="; ".join(corrected),
        )


def migrate_profiles_and_movements(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserProfile = apps.get_model("inventory", "UserProfile")
    Movement = apps.get_model("inventory", "Movement")
    AuditLog = apps.get_model("inventory", "AuditLog")

    existing_profile_users = set(
        UserProfile.objects.values_list("user_id", flat=True)
    )
    UserProfile.objects.bulk_create(
        [
            UserProfile(user_id=user_id)
            for user_id in User.objects.values_list("pk", flat=True)
            if user_id not in existing_profile_users
        ]
    )

    for movement in Movement.objects.select_related(
        "equipment",
        "consumable",
        "from_location",
        "to_location",
        "from_operator",
        "to_operator",
    ).iterator():
        changes = {}
        if movement.from_location_id or movement.to_location_id:
            changes["location"] = {
                "label": "Местоположение",
                "old": movement.from_location.name if movement.from_location_id else "—",
                "new": movement.to_location.name if movement.to_location_id else "—",
            }
        if movement.from_operator_id or movement.to_operator_id:
            changes["operator"] = {
                "label": "Эксплуатант",
                "old": movement.from_operator.full_name if movement.from_operator_id else "—",
                "new": movement.to_operator.full_name if movement.to_operator_id else "—",
            }

        targets = []
        if movement.equipment_id:
            targets.append(
                (
                    "equipment",
                    "Оборудование",
                    movement.equipment_id,
                    f"{movement.equipment.name} "
                    f"({movement.equipment.inventory_number})",
                )
            )
        if movement.consumable_id:
            targets.append(
                (
                    "consumable",
                    "Расходник",
                    movement.consumable_id,
                    movement.consumable.name,
                )
            )
        if not targets:
            targets.append(
                (
                    "movement",
                    "Архивное перемещение",
                    movement.pk,
                    "Перемещение без связанного объекта",
                )
            )

        for object_type, object_label, object_id, object_repr in targets:
            AuditLog.objects.create(
                action="movement",
                object_type=object_type,
                object_type_label=object_label,
                object_id=str(object_id),
                object_repr=object_repr,
                changes=changes,
                note=movement.note,
                actor_id=movement.created_by_id,
                created_at=movement.created_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_consumable_status_alter_disposal_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('repair_started', 'Передано в ремонт'), ('repair_completed', 'Ремонт завершён'), ('movement', 'Архивное перемещение'), ('system', 'Системное событие')], max_length=30, verbose_name='Событие')),
                ('object_type', models.CharField(db_index=True, max_length=100, verbose_name='Тип объекта')),
                ('object_type_label', models.CharField(max_length=150, verbose_name='Раздел')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('object_repr', models.CharField(max_length=500, verbose_name='Объект')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Событие аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at', '-pk'],
                'permissions': [('manage_data_transfer', 'Может импортировать и экспортировать данные')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар')),
                ('notification_level', models.CharField(choices=[('none', 'Не получать'), ('inventory', 'Оборудование и расходники'), ('all', 'Все события журнала')], default='none', max_length=20, verbose_name='Уведомления')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AlterField(
            model_name='disposal',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.RunPython(
            normalize_zero_document_quantities,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='disposal',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='disposal_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='receipt_quantity_gte_1'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='notification',
            name='audit_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.auditlog', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', '-created_at'], name='inventory_a_object__ec2a41_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='inventory_a_actor_i_6d90c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'audit_log'), name='unique_notification_per_event'),
        ),
        migrations.RunPython(migrate_profiles_and_movements, migrations.RunPython.noop),
    ]
