# Generated by Django 5.2.15 on 2026-08-24 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_actor_snapshots(apps, schema_editor):
    AuditLog = apps.get_model("inventory", "AuditLog")
    events = []
    for event in AuditLog.objects.filter(actor__isnull=False).select_related("actor"):
        event.actor_username = event.actor.username
        full_name = f"{event.actor.first_name} {event.actor.last_name}".strip()
        event.actor_display_name = full_name or event.actor.username
        events.append(event)
    if events:
        AuditLog.objects.bulk_update(
            events, ["actor_username", "actor_display_name"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auditlog_notification_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_display_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Логин пользователя'),
        ),
        migrations.RunPython(backfill_actor_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='consumable',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.disposaldirection', verbose_name='Направление ухода'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.operator', verbose_name='Эксплуатация'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id', '-created_at'], name='inventory_a_object__6617b5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='inventory_n_user_id_661d51_idx'),
        ),
    ]
