# Generated by Django 5.2.15 on 2026-08-24 11:30

import django.db.models.functions.text
from django.db import migrations, models


def merge_duplicate_consumable_positions(apps, schema_editor):
    Consumable = apps.get_model("inventory", "Consumable")
    Movement = apps.get_model("inventory", "Movement")
    AuditLog = apps.get_model("inventory", "AuditLog")

    duplicate_groups = (
        Consumable.objects.annotate(
            normalized_name=django.db.models.functions.text.Lower("name")
        )
        .values("equipment_type_id", "location_id", "normalized_name")
        .annotate(count=models.Count("id"), total=models.Sum("quantity"))
        .filter(count__gt=1)
    )
    for group in list(duplicate_groups):
        positions = list(
            Consumable.objects.filter(
                equipment_type_id=group["equipment_type_id"],
                location_id=group["location_id"],
                name__iexact=group["normalized_name"],
            ).order_by("pk")
        )
        primary = positions[0]
        duplicate_ids = [position.pk for position in positions[1:]]
        old_quantity = primary.quantity
        primary.quantity = group["total"]
        primary.save(update_fields=["quantity"])
        Movement.objects.filter(consumable_id__in=duplicate_ids).update(
            consumable_id=primary.pk
        )
        Consumable.objects.filter(pk__in=duplicate_ids).delete()
        AuditLog.objects.create(
            action="system",
            object_type="consumable",
            object_type_label="Расходник",
            object_id=str(primary.pk),
            object_repr=primary.name,
            changes={
                "quantity": {
                    "label": "Количество",
                    "old": str(old_quantity),
                    "new": str(primary.quantity),
                }
            },
            note=f"Объединены дублирующиеся позиции: {duplicate_ids}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auditlog_actor_display_name_auditlog_actor_username_and_more'),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_consumable_positions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('equipment_type'), models.F('location'), condition=models.Q(('location__isnull', False)), name='unique_consumable_position_with_location'),
        ),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('equipment_type'), condition=models.Q(('location__isnull', True)), name='unique_consumable_position_without_location'),
        ),
    ]
