# Generated by Django 5.2.15 on 2026-08-24 11:57

import hashlib
import unicodedata

from django.db import migrations, models


def normalize_and_merge_consumables(apps, schema_editor):
    Consumable = apps.get_model("inventory", "Consumable")
    Movement = apps.get_model("inventory", "Movement")
    AuditLog = apps.get_model("inventory", "AuditLog")
    groups = {}

    for position in Consumable.objects.order_by("pk"):
        normalized_name = unicodedata.normalize(
            "NFKC", position.name or ""
        ).casefold().strip()
        key = (position.equipment_type_id, position.location_id, normalized_name)
        groups.setdefault(key, []).append(position)

    for (_, _, normalized_name), positions in groups.items():
        primary = positions[0]
        duplicate_ids = [position.pk for position in positions[1:]]
        old_quantity = primary.quantity
        primary.normalized_name_hash = hashlib.sha256(
            normalized_name.encode("utf-8")
        ).hexdigest()
        primary.quantity = sum(position.quantity for position in positions)
        primary.save(update_fields=["normalized_name_hash", "quantity"])

        if not duplicate_ids:
            continue
        Movement.objects.filter(consumable_id__in=duplicate_ids).update(
            consumable_id=primary.pk
        )
        Consumable.objects.filter(pk__in=duplicate_ids).delete()
        AuditLog.objects.create(
            action="system",
            object_type="consumable",
            object_type_label="Расходник",
            object_id=str(primary.pk),
            object_repr=primary.name,
            changes={
                "quantity": {
                    "label": "Количество",
                    "old": str(old_quantity),
                    "new": str(primary.quantity),
                }
            },
            note=f"Объединены Unicode-дубли позиций: {duplicate_ids}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_consumable_unique_consumable_position_with_location_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumable',
            name='unique_consumable_position_with_location',
        ),
        migrations.RemoveConstraint(
            model_name='consumable',
            name='unique_consumable_position_without_location',
        ),
        migrations.AddField(
            model_name='consumable',
            name='normalized_name_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.RunPython(normalize_and_merge_consumables, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('normalized_name_hash', 'equipment_type', 'location'), name='unique_consumable_position_with_location'),
        ),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('normalized_name_hash', 'equipment_type'), name='unique_consumable_position_without_location'),
        ),
    ]
